version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
    - image: circleci/python:3.7
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          command: pip install -e ".[tests]"
      - python/save-cache
      - run:
          command: pytest tests
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
